@startuml
package Server{
interface GameFactory {
GameFactory()
buildNewGame()
}
interface WSServer {

}
interface GameManager {
buildColony(idGame : String, idClient : String, idIntersection : integer)
buildRoad(idGame : String, idClient : String, idIntersectionA : integer, idIntersectionB : integer)
BankExchange(rssWantedType : Ressource, rssSoldType : Ressource, idClient : String, idGame : String)
throwDice(idGame : String, idClient String)
upgradeToCity(idGame : String, idClient : String, idIntersection : integer)
endGameTurn(idGame : String, idClient : String)
newGame()
getGame(GameParameters)
connectGame(idGame : String)
}

interface GameConnection {
createGame()
connectGame(idGame : String)
}
interface RESTServer {
createGame()
connectGame(idGame : String)
}
}
package Client{
interface RESTClient {
createGame()
connectGame(idGame : String)
}
interface WSClient {
buildColony(idGame : String, idClient : String, idIntersection : integer)
buildRoad(idGame : String, idClient : String, idIntersectionA : integer, idIntersectionB : integer)
  
bankExchange(rssWantedType : Ressource, rssSoldType : Ressource, idClient : String, idGame : String)
}
interface GameEventHandler {
buildColony(idIntersection : integer)
buildRoad(idIntersectionA : integer, idIntersectionB : integer)  
bankExchange(rssWantedType : Ressource, rssSoldType : Ressource)
throwDice(idGame : String, idClient String)
endGameTurn(idGame : String, idClient : String)
upgradeToCity(idGame : String, idClient : String, idIntersection : integer)
}
interface GUI {
showInGameLobby()
showNewCity()
showDiceResult(diceResult:int)
showEndTurn()
showMyGameTurn()
showNextPlayer()
showEndOfGame()
showWinningGame()
showNewColony(color : String, idIntersection : integer)
showNewRoad(color : String, idIntersectionA : integer, idIntersectionB : integer)
showError(error : String)
showModificationRessources(rss : List<Ressource>, rssAmount : List<Integer>)
createGame()
connectGame(idGame : String)
throwDice()
endGameTurn()
upgradeToCity(idIntersection : integer)
}
interface LobbyHandler {
createGame()
connectGame(idGame : String)
}
}

@enduml

