@startuml


box "Client" #LightGreen
  participant "GUI" as GUI
  participant "GameEventHandler" as GameEventHandler
  participant "WS Client" as WSClient
end box

box "Server" #LightBlue
  participant "WS Server" as WSServer
  participant "GameManager" as GameManager
end box

activate GameManager
activate WSClient
activate WSServer

hnote across: Part of the EndGameTurn sequence diagram

GameManager --> WSServer : Object: EndGameEvent
deactivate GameManager

group #LightYellow Notify/Update [Only for loosing player]
  
  WSServer --> WSClient : <<GameEvent: EndGameEvent>>
  WSClient --> GameEventHandler : GameEvent: EndGameEvent
  deactivate WSServer
  deactivate WSClient
  activate GameEventHandler
    
  GameEventHandler --> GUI : ShowEndOfGame()
  GameEventHandler --> GUI : ShowLoosingGame()
  deactivate GameEventHandler
end
      
group #LightYellow Notify/Update [Only for winning player]

  WSServer --> WSClient : <<GameEvent: EndGameEvent>>
  WSClient --> GameEventHandler : GameEvent: EndGameEvent
  deactivate WSServer
  deactivate WSClient
  activate GameEventHandler
    
  GameEventHandler --> GUI : ShowEndOfGame()
  GameEventHandler --> GUI : ShowWinningGame()
  deactivate GameEventHandler
end

@enduml