= Interface Partie

[options="header"]
|===
|Méthode |Documentation

|`void construireColonie(Joueur joueur, int idIntersection)`
a|
Construit une colonie de la `Couleur` du `joueur` donné, à l' `intersection` donnée.
Appelle `Plateau.construireColonie()`.

Exceptions :

- `GameStatusException` si le joueur ne peut pas jouer.
- `IllegalParameterException` si l'intersection est invalide.
- `ImpossibleBuildException` si l'intersection est déjà occupée ou si elle n'est pas à deux routes minimum d'une autre colonie.
- `NotEnoughRessourcesException` si le joueur n'a pas les ressources nécessaires.


|`void construireVille(Joueur joueur, int idIntersection)`
a|
Améliore une colonie au niveau de ville. Cette ville se trouve à l' `intersection`.
Appelle `Plateau.construireVille()`.


Exceptions :

- `GameStatusException` si le joueur ne peut pas jouer.
- `IllegalParameterException` si l'intersection est invalide.
- `ColonyDoesNotExistException` s'il n'y a pas de colonie sur l'intersection.
- `WrongColorException` si la colonie n'appartient pas au joueur.
- `NotEnoughRessourcesException` si le joueur n'a pas les ressources nécessaires.


|`void construireRoute(Joueur joueur, int intersectionA, int intersectionB)`
a| Construit une route de la couleur du joueur entre deux intersections données.

Exceptions :

- `GameStatusException` si le joueur ne peut pas jouer.
- `IllegalParameterException` si une des intersections est invalide.
- `ImpossibleBuildException` si la route n'a pas pu être constuite.
- `NotEnoughRessourcesException` si le joueur n'a pas les ressources nécessaires.


|`Joueur endGameTurn(Joueur joueurAct)`
a| Termine le tour du joueur actuel et renvoie le joueur à qui c'est maintenant le tour.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.


|`private void evalueFinPartie()`
| Calcul le score des joueurs et met fin à la partie si le joueur actuel a plus de 10 points.
Met ce joueur en tant que gagnant si c'est le cas.


|`boolean partieEstTerminee()`
| Renvoie vrai si la partie est terminée.


|`Joueur getGagnant()`
a| Renvoie le gagnant de la partie.

Exceptions :

- `GameStatusException` si la partie n'est pas finie et qu'il n'y a donc pas encore de gagnant.


|`int lancerDes(Joueur joueurAct)`
a| Lance les dés (`DiceThrow.throw()`) et renvoie le résultat.

Si le résultat est 7, appelle pour chaque joueur `joueur.deleteHalfRessources()`.

Si le résultat n'est pas 7, appelle `Plateau.distribuerRessources()` en fonction du résultat des dés.
À l'aide du résultat de cette dernière méthode, distribuer les ressources aux joueurs.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.


|`List<Joueur> jouerVoleur(Joueur joueurAct, int idTuile)`
a| Change le voleur de tuile et renvoie quels joueurs on peut voler.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.
- `IllegalArgumentException` si la tuile n'est pas valide.


|`void volerRessource(Joueur voleur, Joueur victime)`
a| Permet de voler une ressource aléatoire au joueur volé et de la donner au voleur.

Exceptions :

- `GameStatusException` si le voleur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.
- `NotEnoughRessourcesException` si le joueur volé n'a pas de ressources.

|===



= Interface Plateau

[options="header"]
|===
|Méthode |Documentation


|`void construireColonie(Couleur couleur, int idIntersection)`
a| Construit une colonie de la `Couleur` donnée à l'intersection donnée.

Exceptions :

- `IllegalParameterException` si l'intersection est invalide.
- `ImpossibleBuildException` si l'intersection est déjà occupée, si elle n'est pas à deux de distance minimum d'une autre colonie.


|`void construireVille(Couleur couleur, int idIntersection)`
a| Améliore une colonie au niveau de ville. Cette ville se trouve à l' `intersection`.

Exceptions :

- `IllegalParameterException` si l'intersection est invalide.
- `ColonyDoesNotExistException` s'il n'y a pas de colonie sur l'intersection.
- `WrongColorException` si la colonie n'appartient pas au joueur.


|`void construireRoute(Couleur couleur, int intersectionA, int intersectionB)`
a| Construit une route de la couleur donnée entre deux intersections données.

Exceptions :

- `IllegalParameterException` si une des intersections est invalide.
- `ImpossibleBuildException` si la route n'a pas pu être constuite. C'est-à-dire, si il y a déjà une route, ou si elle n'est pas ratachée à une colonie.


|`Map<Couleur,Map<Ressource,Integer>> distribuerRessources(int valeurJeton)`
a| Renvoie un dictionnaire attribuant à une `couleur` un couple `(Ressource,Integer)` indiquant le nombre de ressource
à distribuer au joueur de cette `couleur`.

Récupère les tuiles de numéro `valeurJeton` et appelle `tuile.distribuerRessources()`.
Additionne les deux résultats obtenue et renvoie le résultat.

Si une des tuiles est la tuile où se situe le voleur, `tuile.distribuerRessources()` n'est pas appelé pour cette tuile.

- `IllegalArgumentExeption` si la `valeurJeton` ne correspond à aucune tuile.


|`List<Joueur> jouerVoleur(int idTuile)`
a| Change le voleur de tuile et renvoie quelles couleurs sont sur cette tuile.

Exception :

- `IllegalArgumentException` si la tuile n'est pas valide.

|===


= Interface Intersection

[options="header"]
|===
|Méthode |Documentation

|`Construction getConstruction()`
|Renvoie la construction.

|`void setConstruction(Construction colonie)`
|Permet de set la construction.

|`Map<Intersection, Couleur> getVoisines()`
|Renvoie les intersections voisines.

|===


= Interface Tuile

[options="header"]
|===
|Méthode |Documentation

|`List<Intersection> getIntersections()`
| Renvoie la liste des intersections autour de la tuile.

|`Ressource getRessource()`
| Renvoie la ressource de la tuile.

|`Map<Couleur,Map<Ressource,Integer>> distribuerRessources()`
a| Renvoie un dictionnaire attribuant à une `couleur` un couple `(Ressource,Integer)` indiquant le nombre de ressource
à distribuer au joueur de cette `couleur`.

Récupère les constructions des intersections autour de la tuile.
Pour chacune des ces constructions, récupérer sa couleur et sa `puissance`, et modifier le dictionnaire ainsi :

`result[couleur][ressource] += puissance`, `ressource` étant la ressource de la tuile.

|===


= Interface Joueur

[options="header"]
|===
|Méthode |Documentation

|`Couleur getCouleur()`
| Renvoie la couleur du joueur.

|`int getNbRessources(Ressource ressource)`
| Renvoie le nombre de ressources de type `ressource` du joueur.

|`int getNbAllRessources()`
| Renvoie le nombre de toutes les ressources du joueur.

|`void removeRessources(Ressource ressource, int amount)`
a| Supprime `amount` ressources de type `ressource` au joueur.

Exception :

- `NotEnoughRessourcesException` si le joueur n'a pas `amount` ressources de type `Ressource`.


|`int getPointsVictoire()`
a| Calcul le nombre du points du joueur en prenant en compte ses constructions, ses fiches spéciales
(plus grande armée et route la plus longue), et ses cartes Victoire.


|`Ressource getRessourceAleatoire()`
a| Retourne une ressource aléatoire que le joueur possède.

Exceptions :

- `NotEnoughRessourcesException` si le joueur n'a pas de ressources.

|`void deleteHalfRessources()`
a| Supprime la moitié des ressources du joueur.

Si le joueur a un nombre impair de ressources, on arrondit le nombre de ressources restantes à la borne inférieur. (e.g. pour 9 ressources de base, on se retrouve avec 4.)

Tant qu'on a pas supprimé la moitié des ressource, on supprime la moitié de chaque type de ressource, un par un. Si le nombre de ressources pour un type est impair, on arrondit le nombre de ressources restantes à la borne supérieure (e.g. pour 3 ressources de base, on se retrouve avec 2).

|===


= Interface Construction

[options="header"]
|===
|Méthode |Documentation

|`Couleur getCouleur()`
| Renvoie la couleur de la construction

|`int getPuissance()`
| Renvoie la puissance de la constrution. 1 pour une colonie, 2 pour une ville.

|===
