= Interface Game

[options="header"]
|===
|Méthode |Documentation

|`void buildColony(Player joueur, int idIntersection)`
a|
Construit une colonie de la `Color` du `joueur` donné, à l' `intersection` donnée.

Appelle `Plateau.buildColony()`. Cette méthode retourne un potentiel port.
Si ce port existe, appelle `joueur.addHarbor(port)`.

Exceptions :

- `GameStatusException` si le joueur ne peut pas jouer.
- `IllegalArgumentException` si l'intersection est invalide.
- `ImpossibleBuildException` si l'intersection est déjà occupée ou si elle n'est pas à deux routes minimum d'une autre colonie.
- `NotEnoughResourcesException` si le joueur n'a pas les ressources nécessaires.


|`void buildCity(Player joueur, int idIntersection)`
a|
Améliore une colonie au niveau de ville. Cette ville se trouve à l' `intersection`.
Appelle `Plateau.buildCity()`.


Exceptions :

- `GameStatusException` si le joueur ne peut pas jouer.
- `IllegalArgumentException` si l'intersection est invalide.
- `ImpossibleBuildException` s'il n'y a pas de colonie sur l'intersection ou si la colonie n'appartient pas au joueur.
- `NotEnoughResourcesException` si le joueur n'a pas les ressources nécessaires.


|`void buildRoad(Player joueur, int intersectionA, int intersectionB)`
a| Construit une route de la couleur du joueur entre deux intersections données.

Exceptions :

- `GameStatusException` si le joueur ne peut pas jouer.
- `IllegalParameterException` si une des intersections est invalide.
- `ImpossibleBuildException` si la route n'a pas pu être construite.
- `NotEnoughResourcesException` si le joueur n'a pas les ressources nécessaires.


|`Player endGameTurn(Player joueurAct)`
a| Termine le tour du joueur actuel et renvoie le joueur à qui c'est maintenant le tour.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.


|`private void evaluateEndGame()`
| Calcule le score des joueurs et met fin à la partie si le joueur actuel a plus de 10 points.
Met ce joueur en tant que gagnant si c'est le cas.


|`boolean isGameEnded()`
| Renvoie vrai si la partie est terminée.


|`Player getWinner()`
a| Renvoie le gagnant de la partie.

Exceptions :

- `GameStatusException` si la partie n'est pas finie et qu'il n'y a donc pas encore de gagnant.


|`int throwDices(Player joueurAct)`
a| Lance les dés (`DiceThrow.throw()`) et renvoie le résultat.

Si le résultat est 7, appelle pour chaque joueur `joueur.deleteHalfResources()`.

Si le résultat n'est pas 7, appelle `Plateau.distribuerResources()` en fonction du résultat des dés.
À l'aide du résultat de cette dernière méthode, distribuer les ressources aux joueurs.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.


|`List<Player> playStealer(Player joueurAct, int idTuile)`
a| Change le voleur de tuile et renvoie quels joueurs on peut voler, c'est-à-dire ceux qui ont une construction à une
intersection de la tuile où le voleur se déplace et qui ont des ressources.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.
- `IllegalArgumentException` si la tuile n'est pas valide.


|`void stealResource(Player voleur, Player victime)`
a| Permet de voler une ressource aléatoire au joueur volé et de la donner au voleur.

Exceptions :

- `GameStatusException` si le voleur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.
- `NotEnoughResourcesException` si le joueur volé n'a pas de ressources.


|`void maritimeTrade(Player joueur, Resource rDefausse, Resource rRecup)`
a| Permet à un joueur d'échanger une ressource `rRecup` en défaussant de 2 à 4 ressources `rDeffausse`.

De base, on doit défausser 4 ressources identiques pour en obtenir 1 de son choix.
Si le joueur possède un port de taux d'échange 3-1, on doit en défausser 3.
Si le joueur possède un port de taux d'échange 2-1 pour une ressource spécifique, il peut défausser
deux cartes de cette ressource.

Appelle `joueur.maritimeTrade()`.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.
- `NotEnoughResourcesException` si le joueur n'a pas assez de ressource `rDeffausse`.


|`void monopoly(Player player, Resource resource)`
a| Permet à un joueur de jouer la carte Monopole.

Appelle `player.playDevelopmentCard(MONOPOLY)` pour le joueur actuel.
Appelle `player.deleteResource()` pour tous les joueurs sauf le joueur actuel et donne au joueur actuel la somme des ressources retirées.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel
- `NotEnoughDevelopmentCardException` si le joueur n'a pas de carte Monopole.


|`void yearOfPlenty(Player player, Resource resource1, Resource resource2)`
a| Permet à un joueur de jouer la carte Invention (Year of Plenty).

Appelle `player.playDevelopmentCard(YEAR_OF_PLENTY)`.
Appelle `player.addResource(resource)` pour les deux ressources demandées par le joueur.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel.
- `NotEnoughDevelopmentCardException` si le joueur n'a pas de carte Invention.


|`void roadBuildingCard(Player player)`
a| Permet à un joueur de jouer la carte "Construction de routes".

Appelle `player.playDevelopmentCard(ROAD_BUILDING)`.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel.
- `NotEnoughDevelopmentCardException` si le joueur n'a pas de carte "Construction de routes".


|`void knightCard(Player player)`
a| Permet à un joueur de jouer la carte Chevalier.

Appelle `player.playDevelopmentCard(KNIGHT)`.

Exceptions :

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel.
- `NotEnoughDevelopmentCardException` si le joueur n'a pas de carte Chevalier.


|`void drawDevelopmentCard(Player player)`
a| Permet à un joueur de piocher une carte Développement.

- `GameStatusException` si le joueur donné en paramètre n'est pas le joueur actuel, ou si cette action n'est pas possible pour le joueur actuel.
- `NotEnoughResourcesException` si le joueur n'a pas les ressources nécessaires.

|===



= Interface Board

[options="header"]
|===
|Méthode |Documentation


|`Optional<Port> buildColony(Color couleur, int idIntersection)`
a| Construit une colonie de la `couleur` donnée à l'intersection donnée.

Retourne le potentiel port de l'intersection.

Exceptions :

- `IllegalArgumentException` si l'intersection est invalide.
- `ImpossibleBuildException` si l'intersection est déjà occupée ou si elle n'est pas à deux de distance minimum d'une autre colonie.


|`void buildCity(Color couleur, int idIntersection)`
a| Améliore une colonie au niveau de ville. Cette colonie se trouve à l'intersection d'id `idIntersection`.

Exceptions :

- `IllegalArgumentException` si l'intersection est invalide.
- `ImpossibleBuildException` s'il n'y a pas de colonie sur l'intersection ou si la colonie n'appartient pas au joueur.


|`void buildRoad(Color couleur, int intersectionA, int intersectionB)`
a| Construit une route de la couleur donnée entre deux intersections données.

Exceptions :

- `IllegalArgumentException` si une des intersections est invalide.
- `ImpossibleBuildException` si la route n'a pas pu être constuite. C'est-à-dire, si il y a déjà une route, ou si elle n'est pas ratachée à une colonie.


|`Map<Color,Map<Resource,Integer>> distributeResources(int valeurJeton)`
a| Renvoie un dictionnaire attribuant à une `couleur` un couple `(Resource,Integer)` indiquant le nombre de ressource
à distribuer au joueur de cette `couleur`.

Récupère les tuiles de numéro `valeurJeton` et appelle `tuile.distributeResources()`.
Additionne les deux résultats obtenue et renvoie le résultat.

Si une des tuiles est la tuile où se situe le voleur, `tuile.distributeResources()` n'est pas appelé pour cette tuile.

Exception :

- `IllegalArgumentExeption` si la `valeurJeton` ne correspond à aucune tuile.


|`List<Color> playStealer(int idTuile)`
a| Change le voleur de tuile et renvoie quelles couleurs sont sur cette tuile.

Exception :

- `IllegalArgumentException` si la tuile n'est pas valide.

|`int getRoadLength(Color color)`
| Calcule la route la plus longue pour une couleur.

|===


= Interface Intersection

[options="header"]
|===
|Méthode |Documentation

|`Construction getConstruction()`
|Renvoie la construction.

|`void setConstruction(Construction colonie)`
|Permet de set la construction.

|`Map<Intersection, Color> getNeighbors()`
|Renvoie les intersections voisines.

|`Optional<Port> getHarbor()`
|Renvoie le potentiel port de l'intersection.

|===


= Interface Tile

[options="header"]
|===
|Méthode |Documentation

|`List<Intersection> getIntersections()`
| Renvoie la liste des intersections autour de la tuile.


|`Resource getResource()`
| Renvoie la ressource de la tuile.


|`Map<Color,Map<Resource,Integer>> distributeResources()`
a| Renvoie un dictionnaire attribuant à une `couleur` un couple `(Resource,Integer)` indiquant le nombre de ressources
à distribuer au joueur de cette `couleur`.

Récupère les constructions des intersections autour de la tuile.
Pour chacune de ces constructions, récupérer sa couleur et sa `puissance`, et modifier le dictionnaire ainsi :

`result[couleur][ressource] += puissance`, `ressource` étant la ressource de la tuile.


|`int getTokenValue()`
| Renvoie la valeur du jeton de la tuile.

|===


= Interface Player

[options="header"]
|===
|Méthode |Documentation

|`Color getColor()`
| Renvoie la couleur du joueur.

|`int getNumberOfResources(Resource resource)`
| Renvoie le nombre de ressources de type `ressource` du joueur.

|`int getNbAllResources()`
| Renvoie le nombre de toutes les ressources du joueur.

|`void addResource(Resource resource)`
| Ajoute la `resource` à la main du joueur.


|`void deleteResources(Resource ressource, int amount)`
a| Supprime `amount` ressources de type `ressource` au joueur.

Exception :

- `NotEnoughResourcesException` si le joueur n'a pas `amount` ressources de type `ressource`.


|`int getPointsVictoire()`
a| Calcul le nombre de points du joueur en prenant en compte ses constructions, ses fiches spéciales
(plus grande armée et route la plus longue), et ses cartes Victoire.


|`Resource getRandomResources()`
a| Retourne une ressource aléatoire que le joueur possède.

Exceptions :

- `NotEnoughResourcesException` si le joueur n'a pas de ressources.


|`void deleteHalfResources()`
a| Supprime la moitié des ressources du joueur.

Si le joueur a un nombre impair de ressources, on arrondit le nombre de ressources restantes à la borne inférieur.
(e.g. pour 9 ressources de base, on se retrouve avec 4.)

Tant qu'on n'a pas supprimé la moitié des ressources, on supprime la moitié de chaque type de ressource,
un par un. Si le nombre de ressources pour un type est impair, on arrondit le nombre de ressources restantes
à la borne supérieure (e.g. pour 3 ressources de base, on se retrouve avec 2).


|`void deleteResource(Resource resource)`
| Retire l'entièreté du nombre de ressources de type `resource` et renvoie le nombre de ressources retirées.


|`void maritimeTrade(Resource rDefausse, Resource rRecup)`
a| Permet d'échanger une ressource `rRecup` en défaussant de 2 à 4 ressources `rDeffausse`.

De base, on doit défausser 4 ressources identiques pour en obtenir 1 de son choix.
Si le joueur possède un port de taux d'échange 3-1, on doit en défausser 3.
Si le joueur possède un port de taux d'échange 2-1 pour une ressource spécifique, il peut défausser
deux cartes de cette ressource.

Regarde parmis les ports du joueur le taux d'échange correspondant à la ressource `rDefausse`.
Appelle `port.exchange(ressource)` pour connaître le nombre de cartes que le joueur devra défausser.

Exceptions :

- `NotEnoughResourcesException` si le joueur n'a pas assez de ressource `rDeffausse`.


|`void addHarbour(Harbor harbor)`
a| Ajoute un port de la façon suivante.
Si le port est de taux 2:1 pour une ressource spécifique, ajoute le port pour cette ressource.
Si le port est de taux 3:1, vérifie pour chaque ressource si le taux est avantageux
et l'ajoute pour cette ressource si tel est le cas.
Si le port est de taux 4:1, ne fait rien car c'est le taux d'échange de base.

Appelle `port1.haveBetterRate(port2)` pour savoir si un port a un taux plus avantageux qu'un autre.


|`void playDevelopmentCard(Development type)`
a| "Joue" et supprime de la main d'un joueur une carte Development de type `type`.

Si le `type` de la carte est Chevalier, ajoute 1 au nombre de chevaliers du joueur.

Exceptions :

- `NotEnoughDevelopmentCardException` si le joueur n'a pas de carte Development de type `type`.

|===


= Interface Construction

[options="header"]
|===
|Méthode |Documentation

|`Color getColor()`
| Renvoie la couleur de la construction

|`int getPower()`
| Renvoie la puissance de la construction. 1 pour une colonie, 2 pour une ville.

|===


= Interface Harbor

[options="header"]
|===
|Méthode |Documentation

|`Optional<Resource> getResource()`
| Retourne la potentielle ressource spécifique du port.

|`int exchange(Resource ressource)`
| Retourne le nombre de cartes ressource que le joueur devra défausser s'il veut échanger la `ressource` donnée avec ce port.

|`boolean haveBetterRate(Port other)`
| Compare le taux du port et d'un autre port et renvoie vrai si le premier a un meilleur taux.

|===
