= Conception détaillée

== Travail à réaliser

// ainsi que de décrire comment vous répondez aux différentes exigences non-fonctionnelles.

Objectif::
Spécification détaillée des composants: leur structure (diagramme de classes de conception), ainsi que le comportement de chaque opération fournie par le composants. Le comportement peut-être décrit en utilisant les diagrammes d'activité, d'interaction, les machines d'état, ainsi que OCL.

Moyens::
Appliquez les concepts vus en cours: design patterns, principes GRASP, bonnes pratiques, etc.




== Réponses aux exigences non-fonctionnelles

[NOTE]
====
Expliquez dans cette section les réponses aux différentes exigences non-fonctionnelles spécifiées.
====

=== Concurrence

Dans le cadre de notre projet, nous allons avoir besoin de gérer la concurrence lorsque les joueurs joueront.
En effet, il ne va pas falloir qu'on ait la possibilité qu'il y ait un autre joueur qui joue en même temps que le joueur qui doit jouer son tour.
C'est pour cela que nous allons devoir gérer ce point-là.

=== Performance

Dans le cadre de notre projet, nous devons penser, concevoir et développer ce dernier pour que celui-ci soit réactif et qu'il soit agréable pour l'utilisateur.

Il faudrait également que ce dernier puisse scaler en fonction du nombre de joueurs afin que la performance et l'expérience de jeu reste inchangée pour le joueur.


Corrigé avec https://www.corrector.co/fr/

=== Interopérabilité

NOTE: TODO!


=== Portabilité

Notre système utilise du Java pour le côté serveur et du javascript pour le côté client. Le Java n'est pas un problème à installer sur un serveur web et le javascript peut être lu par n'importe quel navigateur web.

=== Sécurité

Les interractions du client sont limités et transittent par le serveur afin d'empêcher le client de tricher en cours de partie.

==== Exigence de sécurité

Notre système doit être sécurisé, même si nous ne manipulons pas des données sensibles. Pour cela nous devons vérifier l'identité de l'utilisateur.


N'ayant pas à nous occuper de l'authentification de l'utilisateur nous admettons que le système s'occupant de cela est correct et lui-même sécurisé. Nous admettons également que, quelle que soit la plateforme utilisée (web, logiciel, application) le service d'authentification sera le même pour tous.

=== Maintenabilité

La maintenabilité, un grand point du développement logiciel, pour notre projet, afin de garantir ce point, la documentation est essentielle tant celle de la conception que celle présente dans le code.

Pour compléter ce point, la documentation ne sera pas suffisante à elle seule.
En effet, le test du programme réalisé est aussi primordial, il faudra également veiller à utiliser des versions LTS et non expérimentales des frameworks et des librairies utilisées, il faudra aussi qu'elles soient maintenues activement pour maximiser notre maintenabilité.

=== Interface utilisateur

NOTE: TODO!

=== Interface logicielle

NOTE: TODO!

=== Interface ou protocoles de communication

NOTE: TODO!

=== Correction

NOTE: TODO!

== Patrons logiciels utilisés

NOTE: Décrivez dans cette partie les patrons logiciels utilisés pour mettre en œuvre l'application.


=== Patron de conception "A"

NOTE: TODO!

=== Patron architectural "B"

NOTE: TODO!

== Choix techniques - Distribution des processus

[NOTE]
====
Explicitez les différents choix techniques et les réponses technologiques aux différentes contraintes que le système implique.
====

Pour cela nous allons donc vous présenter l'environnement général de développement puis énoncer les 4 contraintes que nous avons déterminées de notre logiciel.

Nous avons fais le choix d'utiliser comme environnement de travail l'IDE eclipse.
Pour la raison que nous connaissons tous très bien cette environnement, ce qui nous permet d'avoir tous le même environnement de développement.

Également, cette IDE permet la gestion d'un projet maven ce qui nous sera parfaitement adapté.

Voici les 4 contraintes que nous avons déterminées :

. L'interface graphique.
. La communication vers la base de données.
. La communication entre les machines.
. La sécurité.
