= Spécification des composants

== Travail à réaliser

Objectif::
Découpage de la solution en composants (ou sous-systèmes) et spécification des interfaces fournies et requises par ces composants

Moyens::
Utilisez des diagrammes d'interaction (séquence, communication) pour décrire l'échange de messages entre les composants pour en déduire leurs interfaces.

.Diagramme de composants
[plantuml]
....
@startuml
  
package "Server" {
  [WS] as WS_server
  WS_server -l- "ServerInteraction"
  "ServerInteraction" <-l- [GameManager]
  WS_server -u-> "ClientInteraction"
  "ClientInteraction" -- [GameManager]

  [GameManager] -l- "CreateInitGame"
  "CreateInitGame" <-l- [GameFactory]

  [GameManager] -- "Create/Join Game"
  "Create/Join Game" <-- [GameConnection]

  [REST] as REST_server
  REST_server -l- "Connect game"
  REST_server -l- "Create game"
  [GameConnection] -d-> "Connect game"
  [GameConnection] -r-> "Create game"
}

WS_server --r-- "GameInteractions"
REST_server --r-- "Create/Join a game"

package "Client" {

  [WS] as WS_client
  [REST] as REST_client
  [GUI] as GUI
  
  WS_client -u- "ClientInteraction "
  [GameEventHandler] -u-> "ClientInteraction "
  WS_client --> "ServerInteraction "
  [GameEventHandler] -- "ServerInteraction "
  [GameEventHandler] -r- "ClientEvent" 
  [GameEventHandler] -u-> "GuiUpdate"
  [GameEventHandler] -d- "Init WebSocket"

  [LobbyHandler] -l-> "Join Game"
  [LobbyHandler] -d-> "Ask game creation"
  [LobbyHandler] -r- "Join/Create Game"
  [LobbyHandler] -u-> "Init WebSocket"

  REST_client -u- "Join Game"
  REST_client -r- "Ask game creation"

  GUI -l-> "ClientEvent"
  GUI -d- "GuiUpdate"
  GUI -d-> "Join/Create Game"
}

WS_client --r--> "GameInteractions"
REST_client --r--> "Create/Join a game"

@enduml
....


.Diagramme de classes des compétences
[plantuml]
----
include::example$pd-example.plantuml[]
----

== Diagramme de séquence

.Connexion à une Game existante à partir d'un identifiant de Game
[plantuml]
----
include::partials$connectGameSequenceDiag.puml[]
----

.Création d'une Game
[plantuml]
----
include::partials$createGameSequenceDiag.puml[]
----

.Construction d'une colonie
[plantuml]
----
include::partials$buildColonySequenceDiag.puml[]
----

.Construction d'une ville, qui est l'upgrade d'une colonie
[plantuml]
----
include::partials$upgradeToCitySequenceDiag.puml[]
----

.Construction d'une route
[plantuml]
----
include::partials$buildRoadSequenceDiag.puml[]
----

.Commerce avec la banque
[plantuml]
----
include::partials$bankExchangeSequenceDiag.puml[]
----

.Lancer des dés
[plantuml]
----
include::throwDiceSequenceDiag.puml[]
----

.Fin du tour (Cf Fin du tour jeu d'un joueur, problème de génération avec PlantUML)
[plantuml]
----
include::endGameTurnSequenceDiag.puml[]
----

.Fin du jeu (Cf Fin du jeu)
[plantuml]
----
include::endGameSequenceDiag.puml[]
----

