= Spécification des composants

== Travail à réaliser

Objectif::
Découpage de la solution en composants (ou sous-systèmes) et spécification des interfaces fournies et requises par ces composants

Moyens::
Utilisez des diagrammes d'interaction (séquence, communication) pour décrire l'échange de messages entre les composants pour en déduire leurs interfaces.

.Diagramme de composants
[plantuml]
....
@startuml

package "Server" {
  [GameFactory]

  [WS] as WS_server
  WS_server -l- "Interaction Partie"
  "Interaction Partie" <--l-- [GameManager]

  [GameManager] -l- "Création & Initialisation Partie"
  "Création & Initialisation Partie" <--l-- [GameFactory]

  [GameManager] -- "Création ou rejoindre une Partie"
  "Création ou rejoindre une Partie" <-- [GameConnection]

  [REST] as REST_server
  REST_server -l- "Connexion Partie"
  REST_server -l- "Création Partie"
  [GameConnection] -d-> "Connexion Partie"
  [GameConnection] -r-> "Création Partie"
}

WS_server ---r--- "Interactions partie"
REST_server ---r--- "Joindre ou créer une partie"


package "Client" {

  [WS] as WS_client
  [REST] as REST_client
  [GUI] as GUI
  
  WS_client -r- "Interaction client-serveur"
  [GameEventHandler] -l-> "Interaction client-serveur"
  
  [LobbyHandler] -l-> "Joindre Partie"
  [LobbyHandler] -d-> "Demander création Partie"
  [LobbyHandler] -r- "Joindre/Création Partie"

  REST_client -u- "Joindre Partie"
  REST_client -r- "Demander création Partie"

  GUI -l- "Miser à jour graphique"
  GUI -u- "Évenement client"
  GUI -d-> "Joindre/Création Partie"
  "Miser à jour graphique" <-u- [GameEventHandler]
  "Évenement client" <-l- [GameEventHandler]
}

WS_client ---r---> "Interactions partie"
REST_client ---r---> "Joindre ou créer une partie"


@enduml
....