:project: Catane
= Analyse du domaine

== Travail à réaliser

Objectif::
Description du jeu _{project}_ sous la forme d'un diagramme de classes conceptuelles et d'actions.

Moyens::
Utilisez une approche itérative pour découvrir toutes les classes conceptuelles et les actions du jeu.

== Introduction 

== Modèle du domaine

[NOTE]
====
Décrivez ici les classes conceptuelles du domaine, ainsi que leurs attributs et associations.
====

.Classes conceptuelles
[plantuml]
....
@startuml
enum Ressources {
bois
argile
laine
blé
minerai
}


enum Couleur {
bleu
blanc
orange
rouge
}

enum Terrain {
Forêts
Collines
Prés
Champs
Montagnes
Déserts
}

enum Taux_Échange {
4:1
3:1
2:1
}

enum Construction {
Colonie
Ville
Route
}


class Partie
class Plateau
class Port{
Taux_Échange taux
Ressources ressource {@Nullable}
}
class Tuile{
Terrain terrain
Resssources ressource
}
class Intersection
class Pion{
Construction type
Couleur couleur
}
class Voleur
class Dés

class Joueur{
Couleur couleur
}

class Cartes
class "Cartes Ressources"{
  Ressources ressource
}
class "Cartes Développement"{
  String description
}



Partie "1" *-- "1" Plateau
Plateau "19" *-- "1" Tuile
Plateau "54" -- "1" Intersection

Intersection "0:1" *-- "0.1" Port

Intersection "6" -- "1:3" Tuile
Intersection "0:1" -- "1" Pion
Tuile "0:1" -- "1" Voleur

Partie "2" -- "1"  Dés
Partie "many" -- "1" Cartes

Cartes <|-- "Cartes Ressources"
Cartes <|-- "Cartes Développement"

Joueur "many" -- "0:1" Pion : Possède

Partie "3:4" -- "1" Joueur
Joueur "many" -- "0:1" Cartes : Possède
@enduml
....

== Cas d'utilisation

[NOTE]
====
Utilisez le canevas proposé par Alistar Cockburn pour décrire les cas d'utilisation.

Additionnellement, utilisez des diagrammes d'activités UML pour illustrer les cas d'utilisation.
====

=== Cas d'utilisation "Mise en place d'une partie"

include::setup.adoc[leveloffset=2]
include::setup_beginner.adoc[leveloffset=2]

.Diagramme d'activités: Mise en place d'une partie
[plantuml]
....
include::example$ad-mise-en-place.puml[]
....

=== Cas d'utilisation "Tour de jeu"

include::gameTurn.adoc[leveloffset=2]

.Diagramme d'activités: Cas d'utilisation B
[plantuml]
....
include::example$ad-mise-en-place.puml[]
....

== Activités

[NOTE]
====

====

== Opérations

// include::uc-template.adoc[]