:project: Catane
= Analyse du domaine

== Travail à réaliser

Objectif::
Description du jeu _{project}_ sous la forme d'un diagramme de classes conceptuelles et d'actions.

Moyens::
Utilisez une approche itérative pour découvrir toutes les classes conceptuelles et les actions du jeu.

== Introduction 

== Modèle du domaine

[NOTE]
====
Décrivez ici les classes conceptuelles du domaine, ainsi que leurs attributs et associations.
====

.Classes conceptuelles
[plantuml]
....
@startuml

enum Ressources {
Bois
Argile
Laine
Blé
Minerai
}

enum Couleur {
Bleu
Blanc
Orange
Rouge
}

enum Taux_Échange {
4:1
3:1
2:1
}

class Partie
class Plateau

class Port{
Taux_Échange taux
Ressources ressource {@Nullable}
}

class Tuile{
Resssources ressource
int valeurJeton
}

class Intersection

class Joueur{
Couleur couleur
}

class Cartes
class CartesRessources{
  Ressources ressource
}
class CartesDéveloppement{
  String description
}

class Construction {
  Couleur couleur
}
class Colonie
class Ville


Partie *--> "1" Plateau
Plateau *--> "19" Tuile
Plateau *--> "54" Intersection

Construction <|-- Ville
Construction <|-- Colonie

Intersection *--> "0:1" Construction
Intersection --> "2:3" Intersection : routes: Map<Intersection, Couleur>
Intersection "6" <-- Tuile
Intersection *--> "0.1" Port

Partie --> "0:n" Cartes

Cartes <|-- CartesRessources
Cartes <|-- CartesDéveloppement

Partie --> "3:4" Joueur
Joueur --> "0:n" Cartes
Joueur --> "0:5" Port
Joueur --> "0:n" Construction

@enduml

....

== Cas d'utilisation

[NOTE]
====
Utilisez le canevas proposé par Alistar Cockburn pour décrire les cas d'utilisation.

Additionnellement, utilisez des diagrammes d'activités UML pour illustrer les cas d'utilisation.
====

=== Cas d'utilisation "Mise en place d'une partie"

include::setup.adoc[leveloffset=2]
include::setup_beginner.adoc[leveloffset=2]

.Diagramme d'activités: Mise en place d'une partie
[plantuml]
....
include::example$mise-en-place.plantuml[]
....

=== Cas d'utilisation "Tour de jeu"

include::gameTurn.adoc[leveloffset=2]

.Diagramme d'activités: Cas d'utilisation B
[plantuml]
....
include::example$ad-mise-en-place.puml[]
....

== Activités

[NOTE]
====

====

== Opérations

// include::uc-template.adoc[]
